@startsalt
scale 2
{* _ | [] | X }
{#
   
    {+
        {
            <&heart>
        }|
        {
            <b> CORAZÓN
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    } |
    {+
        {
        <&sun>
        }|
        {
            <b> SOL
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    }|
    {+
        {
        <&sun>
        }|
        {
            <b> SOL
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    }
    {+
        {
            <&heart>
        }|
        {
            <b> CORAZÓN
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    } |
    {+
        {
        <&sun>
        }|
        {
            <b> SOL
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    }|
    {+
        {
        <&sun>
        }|
        {
            <b> SOL
            <b>Propietaria ó Propietario
            Norma Inés
            <b>Suplente
            Zain Moráles
        }
    }
}
@endsalt